# Generated by Django 5.2.4 on 2025-07-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime_covers/', verbose_name='Imagen miniatura')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='anime_covers/full/', verbose_name='Imagen de portada')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='URL del tráiler')),
                ('status', models.CharField(choices=[('airing', 'En emisión'), ('completed', 'Finalizado'), ('upcoming', 'Próximamente')], default='upcoming', max_length=10, verbose_name='Estado')),
                ('anime_type', models.CharField(choices=[('tv', 'Serie TV'), ('movie', 'Película'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Especial')], default='tv', max_length=10, verbose_name='Tipo')),
                ('episodes', models.PositiveIntegerField(default=0, verbose_name='Número de episodios')),
                ('duration', models.PositiveIntegerField(default=24, verbose_name='Duración por episodio (minutos)')),
                ('rating', models.FloatField(default=0.0, verbose_name='Puntuación')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de estreno')),
                ('season', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temporada')),
                ('studio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estudio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('genres', models.ManyToManyField(related_name='animes', to='anime.genre', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Viendo'), ('completed', 'Completado'), ('plan_to_watch', 'Planeo ver'), ('on_hold', 'En pausa'), ('dropped', 'Abandonado')], max_length=15, verbose_name='Estado')),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Puntuación (0-10)')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Episodios vistos')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to='anime.anime', verbose_name='Anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_lists', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista de anime',
                'verbose_name_plural': 'Listas de anime',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
