# Generated by Django 5.2.4 on 2025-07-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranimelist',
            name='status',
            field=models.CharField(choices=[('por_ver', 'Por ver'), ('viendo', 'Viendo'), ('finalizado', 'Finalizado')], default='por_ver', max_length=15, verbose_name='Estado'),
        ),
    ]
